### ISSUE TITLE
How to access the game data? How to review game logs?

### ISSUE THREAD

**Issue by erikbgithub** [JavascriptBattle/hero-starter#20]
Wouldn't I need some kind of documentation for either of these to get started? Have I simply not seen it or is it not there yet?

**Comment by gjtrowbridge** [comment]
The game rules, etc are covered on the site itself (in the "rules" tab of the "basics" section).  However, my impression is that you want to be able to see the gameData object and potentially log the results of your own code, etc?

If that's the case, the best way to do either of these is to clone this repo (which I assume you've done), then run the "test_your_hero_code.js" script (instructions at the bottom of this repo's readme).  This script will run a mock game that, while not secured/protected in the same way that the "official" games are, is otherwise identical in structure to a "real" game.  So you can log from the game code itself, log from your hero code, etc, however you like.

We're working on a slightly more user-friendly test site that will allow users to upload code directly just for testing purposes, but that's not ready quite yet.

Does that answer your question?

**Comment by erikbgithub** [comment]
What I want is to see where the other guys on the maps are. How else can I make a decision about where to go?
Thanks for the fast answer, btw. :-)

**Comment by gjtrowbridge** [comment]
Ah, got it!  When you run the "test_your_hero_code.js" function, each turn is resolved by passing the entire game object to your "move" function as the first argument.  This object will include all information about the game, including your health, surrounding heroes, their health, your position, etc.  So the easiest way to find that information out is to look at that object that's getting passed to your move function.

That being said, I don't believe we currently have an easy way for users to find that information without running the test script, so we'll work on putting some more information online to hopefully make that a bit less work.  I'll follow up on here when we put that up (hopefully in the next hour or so).  Cheers!

**Comment by erikbgithub** [comment]
Alright. Thanks for the info!

**Comment by gjtrowbridge** [comment]
@erikb85 Just put up a bit more information on the Wiki for the this repository.  Hopefully that makes it a bit easier to track down info on the game object.
