### ISSUE TITLE
No game for me

### ISSUE THREAD

**Issue by Alfredo-Delgado** [JavascriptBattle/hero-starter#37]
I don't seem to have been placed in a game, since yesterday. [My code](https://github.com/Alfredo-Delgado/hero-starter) works locally and on the test site. When I log on, I get a blank game board and my stats haven't changed.

![screen shot 2014-10-15 at 8 47 25](https://cloud.githubusercontent.com/assets/798836/4645544/54a26054-546a-11e4-8b58-2c5dba7871f2.png)

**Comment by forrestbthomas** [comment]
Hey Alfredo,
Yes, unfortunately we are still tracking down a couple of bugs, including this one. It seems that not all games are being run every night, so your game probably wasn't run, thus the blank screen. We apologize for that and hope to have that bug squashed soon.
Thanks so much for bearing with us while we sort it out.
Cheers,
Forrest

**Comment by gjtrowbridge** [comment]
Thanks for your patience on this!  We finally found time to update our web-workers code yesterday, and to the best of my knowledge this bug is now **resolved**.

All games are now running correctly, so all users will be able to see their hero fight every day from here on out.

This was the cause, if you're interested:
- Our Mongo replica set has an odd tendency to drop connections at random times (such as mid-way through running & saving a battle, so some battles weren't getting finished each day).
- To fix this, we needed to rewrite our app to be smarter about handling dropped connections and to manually reconnect in case of errors (the 'auto_reconnect' and 'keepAlive' options alone were not sufficient to prevent these dropped connections).
- If you're interested, you can check out the mongo wrapper class that we created to solve this issue [here](https://github.com/gjtrowbridge/safe-mongo-connection/blob/master/SafeMongoConnection.js)

**Thanks again for supporting JavaScript Battle!**
