### ISSUE TITLE
Website doesn't show the battle grid

### ISSUE THREAD

**Issue by sagarjauhari** [JavascriptBattle/hero-starter#38]
I'm logged in, but can't see the battle grid. All I see is some misrendered page elements with an error: 

<pre>
 Hero not doing anything? Make sure to check your code for endless loops and errors!
Can't see your hero? Don't forget to login!
</pre>

**Comment by robertpdx** [comment]
Same thing here.  A member of the dev team responded that there are some bugs such that the system is not running everyone's code every day.

**Comment by forrestbthomas** [comment]
Hey all,

Apologies for the bug. We have been swamped this week, but are looking to have this resolved this weekend if not sooner. We are also putting up an announcement on the website soon, so that everyone knows about the bug.
Thanks so much for your patience as we resolve the issue. 

Cheers,
Forrest

**Comment by gjtrowbridge** [comment]
Thanks for your patience on this!  We finally found time to update our web-workers code yesterday, and to the best of my knowledge this bug is now **resolved**.

All games are now running correctly, so all users should be able to see their hero fight every day from here on out (though please do let us know if you're still seeing issues).

This was the cause, if you're interested:
- Our Mongo replica set has an odd tendency to drop connections at random times (such as mid-way through running & saving a battle, so some battles weren't getting finished each day).
- To fix this, we needed to rewrite our app to be smarter about handling dropped connections and to manually reconnect in case of errors (the 'auto_reconnect' and 'keepAlive' options alone were not sufficient to prevent these dropped connections).
- If you're interested, you can check out the mongo wrapper class that we created to solve this issue [here](https://github.com/gjtrowbridge/safe-mongo-connection/blob/master/SafeMongoConnection.js)

**Thanks again for supporting JavaScript Battle!**
